apiVersion: velero.io/v1
kind: Backup
metadata:
  name: my-test-backup
  namespace: velero  # or your velero namespace (e.g. platform-disaster-recovery)
spec:
  includedNamespaces:
    - default
  storageLocation: default
  ttl: 72h0m0s
