apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: velero
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # or use NodePort if LoadBalancer is not supported
