apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-world-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
  persistentVolumeReclaimPolicy: Retain
