apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
